### ISSUE TITLE
Swapped rx and tx pins?

### ISSUE THREAD

**Issue by ejdudley** [douggilliland/MultiComp#1]
Hi - I've been following your youtube videos and couldn't get program loading to work.
I think the pin mapping for rx and tx may have been swapped for the UK101_VGA_PS2_IntRAM(34K) running on MultiComp_On_EP4CE10?
Thanks

**Comment by douggilliland** [comment]
Fixed and tested. Thanks!
https://github.com/douggilliland/MultiComp/commit/8992ee263ea791ebb33c0c5efab19cb2db1b9af7#diff-fd942810e87864e2cf24d540a14746e4
